export const GetPaymentMethod = {
    GET_PAYMENT_SUCCESS: "GET_PAYMENT_SUCCESS",
    GET_PAYMENT_FAILURE: "GET_PAYMENT_FAILURE",

    GET_PAYMENT_BY_ID_SUCCESS: "GET_PAYMENT_BY_ID_SUCCESS",
    GET_PAYMENT_BY_ID_FAILURE: "GET_PAYMENT_BY_ID_FAILURE"
}

export const PostPaymentMethod = {
    POST_PAYMENT_SUCCESS: "POST_PAYMENT_SUCCESS",
    POST_PAYMENT_FAILURE: "POST_PAYMENT_FAILURE"
}

export const UpdatePaymentMethod = {
    UPDATE_PAYMENT_BY_ID_SUCCESS: "UPDATE_PAYMENT_SUCCESS",
    UPDATE_PAYMENT_BY_ID_FAILURE: "UPDATE_PAYMENT_FAILURE"
}

export const DeletePaymentMethod = {
    DELETE_PAYMENT_BY_ID_SUCCESS: "DELETE_PAYMENT_BY_ID_SUCCESS",
    DELETE_PAYMENT_BY_ID_FAILURE: "DELETE_PAYMENT_BY_ID_FAILURE"
}