export const GetEmployeeMethod = {
    GET_EMPLOYEE_SUCCESS: "GET_EMPLOYEE_SUCCESS",
    GET_EMPLOYEE_FAILURE: "GET_EMPLOYEE_FAILURE",

    GET_EMPLOYEE_BY_ID_SUCCESS: "GET_EMPLOYEE_BY_ID_SUCCESS",
    GET_EMPLOYEE_BY_ID_FAILURE: "GET_EMPLOYEE_BY_ID_FAILURE"
}

export const PostEmployeeMethod = {
    POST_EMPLOYEE_SUCCESS: "POST_EMPLOYEE_SUCCESS",
    POST_EMPLOYEE_FAILURE: "POST_EMPLOYEE_FAILURE"
}

export const UpdateEmployeeMethod = {
    UPDATE_EMPLOYEE_BY_ID_SUCCESS: "UPDATE_EMPLOYEE_SUCCESS",
    UPDATE_EMPLOYEE_BY_ID_FAILURE: "UPDATE_EMPLOYEE_FAILURE"
}

export const DeleteEmployeeMethod = {
    DELETE_EMPLOYEE_BY_ID_SUCCESS: "DELETE_EMPLOYEE_BY_ID_SUCCESS",
    DELETE_EMPLOYEE_BY_ID_FAILURE: "DELETE_EMPLOYEE_BY_ID_FAILURE"
}